version: '3'

services:
  db:
    container_name: postgres_db
    image: postgres

  django:
    container_name: django_app
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
